name: Sync Repo for Vercel

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Push to personal repo
        env:
          GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          git config --global user.email "lucasbertolo2@gmail.com"
          git config --global user.name "lucasbertolo"
          git remote add vercel git@github.com:bdj-house/idalgo_cortijo.git
          git push -f vercel main:main
