name: Sync to personal

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout org repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to personal repo
        run: |
          git config user.name "lucasbertolo"
          git config user.email "lucasbertolo2@gmail.com"
          git remote add personal git@github.com:lucasbertolo/idalgo_cortijo.git
          git push personal main --force
